// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/category/category.proto

/*
Package go_micro_service_category is a generated protocol buffer package.

It is generated from these files:
	proto/category/category.proto

It has these top-level messages:
	CategoryRequest
	CreateCategoryResponse
	UpdateCategoryResponse
	DeleteCategoryRequest
	DeleteCategoryResponse
	FindByNameRequest
	CategoryResponse
	FindByIDRequest
	FindByLevelRequest
	FindByParentRequest
	FindAllRequest
	FindAllResponse
*/
package go_micro_service_category

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CategoryRequest struct {
	CategoryName        string `protobuf:"bytes,1,opt,name=category_name,json=categoryName" json:"category_name,omitempty"`
	CategoryLevel       uint32 `protobuf:"varint,2,opt,name=category_level,json=categoryLevel" json:"category_level,omitempty"`
	CategoryParent      int64  `protobuf:"varint,3,opt,name=category_parent,json=categoryParent" json:"category_parent,omitempty"`
	CategoryImage       string `protobuf:"bytes,4,opt,name=category_image,json=categoryImage" json:"category_image,omitempty"`
	CategoryDescription string `protobuf:"bytes,5,opt,name=category_description,json=categoryDescription" json:"category_description,omitempty"`
}

func (m *CategoryRequest) Reset()                    { *m = CategoryRequest{} }
func (m *CategoryRequest) String() string            { return proto.CompactTextString(m) }
func (*CategoryRequest) ProtoMessage()               {}
func (*CategoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CategoryRequest) GetCategoryName() string {
	if m != nil {
		return m.CategoryName
	}
	return ""
}

func (m *CategoryRequest) GetCategoryLevel() uint32 {
	if m != nil {
		return m.CategoryLevel
	}
	return 0
}

func (m *CategoryRequest) GetCategoryParent() int64 {
	if m != nil {
		return m.CategoryParent
	}
	return 0
}

func (m *CategoryRequest) GetCategoryImage() string {
	if m != nil {
		return m.CategoryImage
	}
	return ""
}

func (m *CategoryRequest) GetCategoryDescription() string {
	if m != nil {
		return m.CategoryDescription
	}
	return ""
}

type CreateCategoryResponse struct {
	Message    string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	CategoryId int64  `protobuf:"varint,2,opt,name=category_id,json=categoryId" json:"category_id,omitempty"`
}

func (m *CreateCategoryResponse) Reset()                    { *m = CreateCategoryResponse{} }
func (m *CreateCategoryResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateCategoryResponse) ProtoMessage()               {}
func (*CreateCategoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateCategoryResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateCategoryResponse) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

type UpdateCategoryResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *UpdateCategoryResponse) Reset()                    { *m = UpdateCategoryResponse{} }
func (m *UpdateCategoryResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateCategoryResponse) ProtoMessage()               {}
func (*UpdateCategoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UpdateCategoryResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DeleteCategoryRequest struct {
	CategoryId int64 `protobuf:"varint,1,opt,name=category_id,json=categoryId" json:"category_id,omitempty"`
}

func (m *DeleteCategoryRequest) Reset()                    { *m = DeleteCategoryRequest{} }
func (m *DeleteCategoryRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteCategoryRequest) ProtoMessage()               {}
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeleteCategoryRequest) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

type DeleteCategoryResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *DeleteCategoryResponse) Reset()                    { *m = DeleteCategoryResponse{} }
func (m *DeleteCategoryResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteCategoryResponse) ProtoMessage()               {}
func (*DeleteCategoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeleteCategoryResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type FindByNameRequest struct {
	CategoryName string `protobuf:"bytes,1,opt,name=category_name,json=categoryName" json:"category_name,omitempty"`
}

func (m *FindByNameRequest) Reset()                    { *m = FindByNameRequest{} }
func (m *FindByNameRequest) String() string            { return proto.CompactTextString(m) }
func (*FindByNameRequest) ProtoMessage()               {}
func (*FindByNameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *FindByNameRequest) GetCategoryName() string {
	if m != nil {
		return m.CategoryName
	}
	return ""
}

type CategoryResponse struct {
	Id                  int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	CategoryName        string `protobuf:"bytes,2,opt,name=category_name,json=categoryName" json:"category_name,omitempty"`
	CategoryLevel       uint32 `protobuf:"varint,3,opt,name=category_level,json=categoryLevel" json:"category_level,omitempty"`
	CategoryParent      int64  `protobuf:"varint,4,opt,name=category_parent,json=categoryParent" json:"category_parent,omitempty"`
	CategoryImage       string `protobuf:"bytes,5,opt,name=category_image,json=categoryImage" json:"category_image,omitempty"`
	CategoryDescription string `protobuf:"bytes,6,opt,name=category_description,json=categoryDescription" json:"category_description,omitempty"`
}

func (m *CategoryResponse) Reset()                    { *m = CategoryResponse{} }
func (m *CategoryResponse) String() string            { return proto.CompactTextString(m) }
func (*CategoryResponse) ProtoMessage()               {}
func (*CategoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CategoryResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CategoryResponse) GetCategoryName() string {
	if m != nil {
		return m.CategoryName
	}
	return ""
}

func (m *CategoryResponse) GetCategoryLevel() uint32 {
	if m != nil {
		return m.CategoryLevel
	}
	return 0
}

func (m *CategoryResponse) GetCategoryParent() int64 {
	if m != nil {
		return m.CategoryParent
	}
	return 0
}

func (m *CategoryResponse) GetCategoryImage() string {
	if m != nil {
		return m.CategoryImage
	}
	return ""
}

func (m *CategoryResponse) GetCategoryDescription() string {
	if m != nil {
		return m.CategoryDescription
	}
	return ""
}

type FindByIDRequest struct {
	CategoryId int64 `protobuf:"varint,1,opt,name=category_id,json=categoryId" json:"category_id,omitempty"`
}

func (m *FindByIDRequest) Reset()                    { *m = FindByIDRequest{} }
func (m *FindByIDRequest) String() string            { return proto.CompactTextString(m) }
func (*FindByIDRequest) ProtoMessage()               {}
func (*FindByIDRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *FindByIDRequest) GetCategoryId() int64 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

type FindByLevelRequest struct {
	Level uint32 `protobuf:"varint,1,opt,name=level" json:"level,omitempty"`
}

func (m *FindByLevelRequest) Reset()                    { *m = FindByLevelRequest{} }
func (m *FindByLevelRequest) String() string            { return proto.CompactTextString(m) }
func (*FindByLevelRequest) ProtoMessage()               {}
func (*FindByLevelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *FindByLevelRequest) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

type FindByParentRequest struct {
	ParentId int64 `protobuf:"varint,1,opt,name=parent_id,json=parentId" json:"parent_id,omitempty"`
}

func (m *FindByParentRequest) Reset()                    { *m = FindByParentRequest{} }
func (m *FindByParentRequest) String() string            { return proto.CompactTextString(m) }
func (*FindByParentRequest) ProtoMessage()               {}
func (*FindByParentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *FindByParentRequest) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

type FindAllRequest struct {
}

func (m *FindAllRequest) Reset()                    { *m = FindAllRequest{} }
func (m *FindAllRequest) String() string            { return proto.CompactTextString(m) }
func (*FindAllRequest) ProtoMessage()               {}
func (*FindAllRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type FindAllResponse struct {
	Category []*CategoryResponse `protobuf:"bytes,1,rep,name=category" json:"category,omitempty"`
}

func (m *FindAllResponse) Reset()                    { *m = FindAllResponse{} }
func (m *FindAllResponse) String() string            { return proto.CompactTextString(m) }
func (*FindAllResponse) ProtoMessage()               {}
func (*FindAllResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *FindAllResponse) GetCategory() []*CategoryResponse {
	if m != nil {
		return m.Category
	}
	return nil
}

func init() {
	proto.RegisterType((*CategoryRequest)(nil), "go.micro.service.category.CategoryRequest")
	proto.RegisterType((*CreateCategoryResponse)(nil), "go.micro.service.category.CreateCategoryResponse")
	proto.RegisterType((*UpdateCategoryResponse)(nil), "go.micro.service.category.UpdateCategoryResponse")
	proto.RegisterType((*DeleteCategoryRequest)(nil), "go.micro.service.category.DeleteCategoryRequest")
	proto.RegisterType((*DeleteCategoryResponse)(nil), "go.micro.service.category.DeleteCategoryResponse")
	proto.RegisterType((*FindByNameRequest)(nil), "go.micro.service.category.FindByNameRequest")
	proto.RegisterType((*CategoryResponse)(nil), "go.micro.service.category.CategoryResponse")
	proto.RegisterType((*FindByIDRequest)(nil), "go.micro.service.category.FindByIDRequest")
	proto.RegisterType((*FindByLevelRequest)(nil), "go.micro.service.category.FindByLevelRequest")
	proto.RegisterType((*FindByParentRequest)(nil), "go.micro.service.category.FindByParentRequest")
	proto.RegisterType((*FindAllRequest)(nil), "go.micro.service.category.FindAllRequest")
	proto.RegisterType((*FindAllResponse)(nil), "go.micro.service.category.FindAllResponse")
}

func init() { proto.RegisterFile("proto/category/category.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 546 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xb3, 0x71, 0xd3, 0xa6, 0x53, 0xea, 0x84, 0x6d, 0xa8, 0x4c, 0x10, 0x22, 0x5a, 0x84,
	0x08, 0x05, 0x0c, 0x35, 0x17, 0xae, 0xd0, 0x08, 0x14, 0x09, 0x21, 0x64, 0xc4, 0x85, 0x0b, 0x32,
	0xf1, 0x28, 0x32, 0x8a, 0x3f, 0x6a, 0x9b, 0x22, 0x1e, 0x87, 0x37, 0xe3, 0x15, 0x78, 0x03, 0xe4,
	0xdd, 0xec, 0x3a, 0x76, 0x5c, 0xc7, 0x46, 0xdc, 0xb2, 0xb3, 0x33, 0xf3, 0x9b, 0xd9, 0x99, 0x7f,
	0x0c, 0x77, 0xa3, 0x38, 0x4c, 0xc3, 0x67, 0x0b, 0x27, 0xc5, 0x65, 0x18, 0xff, 0x54, 0x3f, 0x4c,
	0x6e, 0xa7, 0xb7, 0x97, 0xa1, 0xe9, 0x7b, 0x8b, 0x38, 0x34, 0x13, 0x8c, 0xaf, 0xbc, 0x05, 0x9a,
	0xd2, 0x81, 0xfd, 0x26, 0x30, 0xb8, 0x58, 0x1f, 0x6c, 0xbc, 0xfc, 0x8e, 0x49, 0x4a, 0xef, 0xc3,
	0xb1, 0xbc, 0xff, 0x12, 0x38, 0x3e, 0x1a, 0x64, 0x42, 0xa6, 0x87, 0xf6, 0x0d, 0x69, 0x7c, 0xef,
	0xf8, 0x48, 0x1f, 0x80, 0xae, 0x9c, 0x56, 0x78, 0x85, 0x2b, 0xa3, 0x3b, 0x21, 0xd3, 0x63, 0x5b,
	0x85, 0xbe, 0xcb, 0x8c, 0xf4, 0x21, 0x0c, 0x94, 0x5b, 0xe4, 0xc4, 0x18, 0xa4, 0x86, 0x36, 0x21,
	0x53, 0xcd, 0x56, 0xd1, 0x1f, 0xb8, 0xb5, 0x90, 0xcf, 0xf3, 0x9d, 0x25, 0x1a, 0x7b, 0x9c, 0xaa,
	0xf2, 0xcd, 0x33, 0x23, 0x3d, 0x87, 0x91, 0x72, 0x73, 0x31, 0x59, 0xc4, 0x5e, 0x94, 0x7a, 0x61,
	0x60, 0xf4, 0xb8, 0xf3, 0x89, 0xbc, 0x9b, 0xe5, 0x57, 0xec, 0x23, 0x9c, 0x5e, 0xc4, 0xe8, 0xa4,
	0x98, 0xf7, 0x99, 0x44, 0x61, 0x90, 0x20, 0x35, 0xe0, 0xc0, 0xc7, 0x24, 0xc9, 0x60, 0xa2, 0x45,
	0x79, 0xa4, 0xf7, 0xe0, 0x28, 0xaf, 0xc6, 0xe5, 0xad, 0x69, 0x36, 0xa8, 0x52, 0x5c, 0x66, 0xc1,
	0xe9, 0xa7, 0xc8, 0x6d, 0x95, 0x94, 0xbd, 0x84, 0x5b, 0x33, 0x5c, 0xe1, 0x66, 0x8c, 0x78, 0xf0,
	0x12, 0x8d, 0x54, 0xd1, 0xca, 0x91, 0x0d, 0x68, 0x37, 0xdf, 0x78, 0x81, 0xfb, 0x9a, 0x8f, 0xab,
	0xcd, 0x68, 0xd9, 0x1f, 0x02, 0xc3, 0x2d, 0x90, 0x0e, 0x5d, 0x55, 0x5a, 0xd7, 0x73, 0xb7, 0x33,
	0x75, 0x1b, 0x2d, 0x89, 0xd6, 0x70, 0x49, 0xf6, 0x1a, 0x2e, 0x49, 0xaf, 0xcd, 0x92, 0xec, 0x5f,
	0xbf, 0x24, 0x16, 0x0c, 0xc4, 0x6b, 0xcd, 0x67, 0x8d, 0xa7, 0x72, 0x06, 0x54, 0xc4, 0xf0, 0x2e,
	0x64, 0xd8, 0x08, 0x7a, 0xa2, 0x55, 0xc2, 0x5b, 0x15, 0x07, 0x66, 0xc1, 0x89, 0xf0, 0x15, 0x9d,
	0x48, 0xe7, 0x3b, 0x70, 0x28, 0x1a, 0xce, 0x09, 0x7d, 0x61, 0x98, 0xbb, 0x6c, 0x08, 0x7a, 0x16,
	0xf3, 0x6a, 0x25, 0x73, 0xb3, 0xcf, 0xa2, 0x4a, 0x6e, 0x59, 0xcf, 0xe5, 0x2d, 0xf4, 0x65, 0x49,
	0x06, 0x99, 0x68, 0xd3, 0x23, 0xeb, 0xb1, 0x79, 0xad, 0xdc, 0xcd, 0xf2, 0x58, 0x6d, 0x15, 0x6c,
	0xfd, 0x3a, 0x80, 0xbe, 0xbc, 0xa6, 0x97, 0xa0, 0x17, 0x35, 0x43, 0xcf, 0x1a, 0x65, 0xe5, 0x65,
	0x8e, 0xcf, 0xeb, 0x7c, 0x2b, 0xa5, 0xc8, 0x3a, 0x19, 0xb2, 0xa8, 0xa8, 0xff, 0x86, 0xac, 0x16,
	0x2a, 0xeb, 0xd0, 0x1f, 0xa0, 0x17, 0x65, 0x45, 0x9f, 0xd7, 0xa4, 0xa9, 0xd4, 0x6e, 0x2d, 0xb8,
	0x5a, 0xb3, 0xbc, 0x57, 0xbe, 0x39, 0xf2, 0x46, 0x68, 0x94, 0x3e, 0xa9, 0x49, 0xb5, 0x25, 0xe5,
	0x71, 0x9b, 0x31, 0xb3, 0x0e, 0xf5, 0x61, 0x58, 0x44, 0xce, 0x67, 0xb5, 0x0f, 0x5c, 0x52, 0x43,
	0x5b, 0x5c, 0x2c, 0xf6, 0x3d, 0xc7, 0x09, 0xa5, 0x3f, 0xdd, 0x49, 0xdc, 0xd4, 0xd2, 0x78, 0x57,
	0x81, 0x1b, 0x42, 0x60, 0x1d, 0x9a, 0xc2, 0xa8, 0xc8, 0x5c, 0xff, 0x6b, 0x98, 0x3b, 0xa1, 0x05,
	0x51, 0xb6, 0xa4, 0x7e, 0x53, 0x9a, 0x54, 0x5b, 0xf4, 0xa8, 0x49, 0x82, 0x7f, 0x60, 0x7d, 0xdd,
	0xe7, 0xdf, 0xf3, 0x17, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x99, 0xf8, 0x78, 0x22, 0xf0, 0x07,
	0x00, 0x00,
}
